### ISSUE TITLE
Unable to download using album url but ok with track urls.

### ISSUE THREAD

**Issue by jeesmell** [Dniel97/orpheusdl-beatport#23]
**link:**
https://www.beatport.com/release/earth-vol-1-original-12-version/1030629

**error:**
 Beatport: Professional subscription detected, allowing high and lossless quality
Traceback (most recent call last):
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\orpheus.py", line 225, in <module>
    main()
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\orpheus.py", line 220, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\orpheus\core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\orpheus\music_downloader.py", line 207, in download_album
    album_info: AlbumInfo = self.service.get_album_info(album_id, **extra_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\modules\beatport\interface.py", line 279, in get_album_info
    album_data = data.get(album_id) if album_id in data else self.session.get_release(album_id)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\modules\beatport\beatport_api.py", line 149, in get_release
    return self._get(f'catalog/releases/{release_id}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DROPBOX15\Fifteen Dropbox\Senior Fiteen\ORPHEUS\modules\beatport\beatport_api.py", line 138, in _get
    raise ConnectionError(r.text)
ConnectionError: {"detail":"No Release matches the given query."}

**however, downloads successfully using track urls from the album.
first track url from the album:**
https://www.beatport.com/track/the-rhyme-goes-on/4100926

**Comment by jeesmell** [comment]
so far any album/track that has a number in it provides the error

![image](https://github.com/user-attachments/assets/92159142-5778-4a0b-9e2c-30883ad7d8b2)

**Comment by tomtom2430** [comment]
Having the same issue here

**Comment by Dniel97** [comment]
Can you try the latest develop commit?

**Comment by jeesmell** [comment]
> Can you try the latest develop commit?

issue fixed. TY

**Comment by jeesmell** [comment]
> Can you try the latest develop commit?

ran into another type of album url format that gives the error again. track urls from the album download ok.

https://www.beatport.com/release/klsunderground001/829913

![image](https://github.com/user-attachments/assets/950bb441-ab91-4c98-a9ff-56d6681eb07e)

**Comment by jeesmell** [comment]
track URL with error.

https://www.beatport.com/track/999/4069419 

![image](https://github.com/user-attachments/assets/ad1aa9af-a1c1-456e-bcad-21ed75b42801)

**Comment by johnneerdael** [comment]
Both at least work perfectly fine on my personal beatport revamped module, because it's a complete rewrite and I want to protect that abusers get their hands on it it's sitting behind a patreon just to ensure it's not abused. On the other hand it also supports a heap more features then this beatport module for Orpheus: [](https://patreon.com/johnneerdael) I would have preferred to give it out in the open but thats what caused beatport previous API changes so I'm a bit more protective. I can also say I use a different logon mechanism then this module and was already supporting FLAC before this module which originally cloned the behavior from the Android app which had no FLAC support, seems now it's switching to a implementation mimicking serato.

**Comment by Dniel97** [comment]
> Both at least work perfectly fine on my personal beatport revamped module, because it's a complete rewrite and I want to protect that abusers get their hands on it it's sitting behind a patreon just to ensure it's not abused.

Okay so you are putting an previous open source repository behind a patron pay wall? Congratulations!

> On the other hand it also supports a heap more features then this beatport module for Orpheus: [link removed]

I don't see where you mention "the heap" of new features?

> I can also say I use a different logon mechanism then this module and was already supporting FLAC before this module which originally cloned the behavior from the Android app which had no FLAC support, seems now it's switching to a implementation mimicking serato.

So considering only DJ programs like Serato, Virtual DJ, Traktor and rekordbox are officially supported, i just doubt you figured that out properly. No FLAC support was added on October 14th thanks to the following PR: #8 and was way before you even created your own repository on November 24: https://github.com/Dniel97/orpheusdl-beatport/issues/21#issuecomment-2495287242

From now on I will personally block your GitHub account and will remove all your (issue) comments.
