### ISSUE TITLE
No Release matches the given query.

### ISSUE THREAD

**Issue by qyraai** [Dniel97/orpheusdl-beatport#25]
Hi,
 I'm getting the below error for some releases from the latest update.

```
 Beatport: Professional subscription detected, allowing high and lossless quality
Traceback (most recent call last):
  File "/home/alwyzon/orfi/OrpheusDL/orpheus.py", line 225, in <module>
    main()
  File "/home/alwyzon/orfi/OrpheusDL/orpheus.py", line 220, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/home/alwyzon/orfi/OrpheusDL/orpheus/core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "/home/alwyzon/orfi/OrpheusDL/orpheus/music_downloader.py", line 207, in download_album
    album_info: AlbumInfo = self.service.get_album_info(album_id, **extra_kwargs)
  File "/home/alwyzon/orfi/OrpheusDL/modules/beatport/interface.py", line 279, in get_album_info
    album_data = data.get(album_id) if album_id in data else self.session.get_release(album_id)
  File "/home/alwyzon/orfi/OrpheusDL/modules/beatport/beatport_api.py", line 149, in get_release
    return self._get(f'catalog/releases/{release_id}')
  File "/home/alwyzon/orfi/OrpheusDL/modules/beatport/beatport_api.py", line 138, in _get
    raise ConnectionError(r.text)
ConnectionError: {"detail":"No Release matches the given query."}
```

Ref: URL 

https://www.beatport.com/release/zoid-vs-musicians-vol-2-remixes/4830378
https://www.beatport.com/release/shinynondefinablerarities02/4832119

Thank you!

**Comment by mathkartel** [comment]
I have fixed the issue by simply adjusting the regex.  

```python
match = re.search(r"https?://(www.)?beatport.com/(?:[a-z]{2}/)?"
                  r"(?P<type>track|release|artist|playlists|chart)/[^/]+/(?P<id>\d+)", link)
```  

This should now correctly match the expected Beatport URLs."

**Comment by tomtom2430** [comment]
Same problem here, can't download some albums with numbers on it's name title: https://www.beatport.com/release/craving-4-u-feat-bbyclose-extended/4806539

**Comment by MAGarcia98** [comment]
Hey - I'm having the same issue. Please see below. I believe it has to do with what the user above mentioned - songs with numebrs on the title.

Tried to use the tool with beatport to download this specific song:

https://www.beatport.com/track/24-turn-it-up/20040833

And got this output error message:

Beatport: Professional subscription detected, allowing high and lossless quality
Traceback (most recent call last):
File "/Users/user1/OrpheusDL/orpheus.py", line 225, in
main()
File "/Users/user1/OrpheusDL/orpheus.py", line 220, in main
orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
File "/Users/user1/OrpheusDL/orpheus/core.py", line 399, in orpheus_core_download
downloader.download_track(media_id, extra_kwargs=media.extra_kwargs)
File "/Users/user1/OrpheusDL/orpheus/music_downloader.py", line 294, in download_track
track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
File "/Users/user1/OrpheusDL/modules/beatport/interface.py", line 318, in get_track_info
track_data = data[track_id] if track_id in data else self.session.get_track(track_id)
File "/Users/user1/OrpheusDL/modules/beatport/beatport_api.py", line 146, in get_track
return self._get(f'catalog/tracks/{track_id}')
File "/Users/user1/OrpheusDL/modules/beatport/beatport_api.py", line 138, in _get
raise ConnectionError(r.text)
ConnectionError: {"detail":"Not found."}
